name: Pylint

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -e .
    - name: Analysing the code with pylint
      run: |
        set +e
        pylint --disable=C0301,C0114 $(git ls-files '*.py')
        set -e
        ret=$?
        [ $ret -gt 50 ] && exit $ret || true
